apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: C0mponent-Name_1234567890.ABCDEFGHIJKLMNOPQRSTUVWXYZ-abcdefghi_
  annotations:
    backstage.io/kubernetes-id: C0mponent-Name_1234567890.ABCDEFGHIJKLMNOPQRSTUVWXYZ-abcdefghi_
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Zaperex-Test-Org/test-repo-3
spec:
  type: other
  lifecycle: production
  owner: group:default/janus-authors